### PR TITLE
Preserve whitespace before and after cursor on auto-trim

### PR DESCRIPTION
**Pull request by velebit**
Change the behavior on auto-trim (only) so that whitespace immediately before and after the cursor is preserved, as suggested by issue #5. Any spaces, tabs and/or newlines adjacent to the cursor are preserved, even if they would normally be affected by the trimming of multiple newlines. If a selection is active, whitespace immediately before, within and after the selection is preserved.

The implementation trims the block before the cursor/selection (but doesn't trim trailing lines in that block), and trims the block after the cursor/selection (but doesn't trim leading lines in that block).

If auto-trim does not remove some whitespace because the cursor is next to it, the auto-trim stays active (keeps firing at the debounce interval) until fully trimmed.

### CODE REVIEW

**Comment by velebit** [comment]
This is not quite ready yet, since currently it doesn't trim _any_ trailing whitespace in the portion before the cursor or _any_ leading whitespace in the portion after the cursor.

**Comment by zlovatt** [comment]
Thanks for hopping on this! I haven't had bandwidth to dive into this in a while, but I was having trouble finding a solution that could handle both ignoring the currently line (or _only_ processing the current line) while still respecting all the multi-line trims.

This was complicated more by trying to preserve multiple selection sets, which other software (like vscode) don't need to deal with as they _only_ trim the current line, and don't have any feature set around trimming multiple lines.

Let me know when you feel it's ready!

**Comment by velebit** [comment]
OK, the immediate problem described above is fixed.

For now, I just capture and preserve any whitespace (including multiline whitespace!) immediately before and immediately after the cursor or selection.  If you think it should only preserve the current line, that would be reasonably easy to change.

There may still be some tricky issues that I'm not sure how to best solve. For example, I'm pretty sure that leaving the cursor in the middle of a code block's "```" start tag will cause code block preservation to break.

What do you think? If you'd like to hold off on this until the plugin gets a unit test suite, I couldn't argue against that...

**Comment by velebit** [comment]
(Just to clarify, I probably can't/shouldn't volunteer to add unit tests myself in the short term.)

**Comment by zlovatt** [comment]
@velebit I'm also seeing the issue of bad code fence detection if the cursor is in the middle of the backtick block. It'd be nice to find a solve for this, but I've hit a wall on the best way around this.

Seems like the best way to go would be to find a way to detect whether the cursor(s) are inside a code fence (including the backticks), and if so to move them to the nearest inside/outside – but I'm not really sure how to execute this 🙃

I've made a branch in this repo ([feature/preserve-whitespace-before-and-after-cursor](https://github.com/zlovatt/obsidian-trim-whitespace/tree/feature/preserve-whitespace-before-and-after-cursor)) combines the current dev branch with your PR.

Any thoughts or input would be appreciated!

**Pull request merged**
